name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update Server Repo
      uses: "maddox/actions/ssh@master"
      env:
        PRIVATE_KEY: |
                    -----BEGIN OPENSSH PRIVATE KEY-----
                    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
                    NhAAAAAwEAAQAAAgEAzqxaSe8ZZNqnw2v/ECny/4J9KmKeBHnIVqHkYHvP9ST/bDvAgvz8
                    ONGtQv9F9ReXTPM/iWEnfnUKW6ji1ghO6DtSCYPQ3tOkS766EseV4DYAteHsSqs8CFZYuX
                    /yRKmwd7oLZwnk/BG5pj5nZG4LDDbu47OAKjADp5ETEqELid4nZ/vt+oA5ICtx+7DJ2hvV
                    J2NR3nk7HiWr9rEHBx8uX1J9va9CUG7cC4zPuwvpbiOhDyrbHBqq+N6hn9srYJ5KvurO/9
                    VOAbv/beioSXvFVVsNUE+JiAoeFK6LzqcRDID8uOjECRWM8XRh38ahZjks9IMl16N8a7I8
                    QfwRp3+Wwi2N8pPK5sgprzakciqYURLi0li1nodV1xXIQr70ryTh0PxXf90KFy3H477rJP
                    9PVGzWKjqibgLiSXyHKpJjfrBHEZX7W3UCb6rpcwBEY1gCC8j1+NnChG3rg885YlUJ4Sqh
                    MuYb9U5KdhtUT4D8TO5KDl0mXCzs3cBBIC8IclkeJENyZ6CrbsqBqS7mxofWweHBJt231M
                    Pyjct10i7ShsryUCyV8vz0J+kuCB1cOs7KSE+k7TRIU0uRQz4HRlWD9rfkiBJpjAI/MZw6
                    pA4t6jVb1750ebheZq2gKFYwRwBp6Vqm0pjVVhIaxU1m6VH3kFXQR8UPFN7ZFCjIu33I6c
                    8AAAdY4OopduDqKXYAAAAHc3NoLXJzYQAAAgEAzqxaSe8ZZNqnw2v/ECny/4J9KmKeBHnI
                    VqHkYHvP9ST/bDvAgvz8ONGtQv9F9ReXTPM/iWEnfnUKW6ji1ghO6DtSCYPQ3tOkS766Es
                    eV4DYAteHsSqs8CFZYuX/yRKmwd7oLZwnk/BG5pj5nZG4LDDbu47OAKjADp5ETEqELid4n
                    Z/vt+oA5ICtx+7DJ2hvVJ2NR3nk7HiWr9rEHBx8uX1J9va9CUG7cC4zPuwvpbiOhDyrbHB
                    qq+N6hn9srYJ5KvurO/9VOAbv/beioSXvFVVsNUE+JiAoeFK6LzqcRDID8uOjECRWM8XRh
                    38ahZjks9IMl16N8a7I8QfwRp3+Wwi2N8pPK5sgprzakciqYURLi0li1nodV1xXIQr70ry
                    Th0PxXf90KFy3H477rJP9PVGzWKjqibgLiSXyHKpJjfrBHEZX7W3UCb6rpcwBEY1gCC8j1
                    +NnChG3rg885YlUJ4SqhMuYb9U5KdhtUT4D8TO5KDl0mXCzs3cBBIC8IclkeJENyZ6Crbs
                    qBqS7mxofWweHBJt231MPyjct10i7ShsryUCyV8vz0J+kuCB1cOs7KSE+k7TRIU0uRQz4H
                    RlWD9rfkiBJpjAI/MZw6pA4t6jVb1750ebheZq2gKFYwRwBp6Vqm0pjVVhIaxU1m6VH3kF
                    XQR8UPFN7ZFCjIu33I6c8AAAADAQABAAACAEClwQhndjYJ/3gti/duZ8hs9OIRPwR/Y59V
                    vK5BjGdOT2d3uVw/7lWHoP7YAvYLjxRO8ozyivwPeFH7nhj9OFGEXMEFLozE/xuCaYn+TG
                    959Pbv2I3yyjCBcfd0gj/gJIcO9wogGjSPBtdtpcHQejwz4r3vJCQOKNZ9ls24+ncBuqnY
                    MDSvby8U5+6m+jzzf9V2R+GjYk6n0ga0kVI0+rhugU6YR9IJG2OxhDkqHLaLBpJMAYXlAZ
                    4fZccvM35hhVf68w0rl98LA3dJ03pI8Q0mEiARASBAqfAmOS1HLRoQLv1YMhn1V8Ufdo4c
                    /9eOAvXpICk3xm+ZrSemxY7zZiB/KggRc80ZtXQh8mP5hFL8oc6IX1CbXfjTON89v5vVlC
                    yxJWmeve+yhT1apaevaSkyay2KmzmhKhDy/DUErxiU0KSt/q/6AecAWWtB8q9A+qqB3QFl
                    PQuj8Bz6XxLN21JtgnnC8iGcexJNw5N3L2J7y9VPw6B/luzTk+DZOgcHsySE1jNhHwNF6t
                    T6DUNP5RhtDCA7wba91C9C/1qzcEGn2aqSb5oSi9duIBQ9Sq+69CftvK3nb2RhrNpV2QGS
                    PYcjP61w0nlhXhtdv3xSxf+Jd80OXSWV9UKmqONgdEMiwwD00M7Lf1OY1tz6cSAV+9lZ9Q
                    qICjTI5PezTK7Grb5hAAABAQCjvgeNsu9/lHkb4zD9UwwHpCwdB19MrlVHgABuy5oYqET5
                    4mOUrme5oBJ47/NoensfCsq1fFlRy+BYNpwbTMITdHEktFILLHtY4Akl4TZLHtw4jmfnyM
                    zAq85D8bSu/t6xrYGsVWVsvwCmqIfBqoVJ6cDUG6IXkHyaFCUg/huvT5sWrN9zHbX+SVeo
                    Urh4W/h047ztV7tU9aOTBPEdsdFj54dFfu4jgRC1gTn+YyBFZ7HLa6n1pBhdHjiDD1OhUQ
                    MwKkk169Mict9jpuJVti439PAeiy4pBfRYc+Dt3hjnMsIcehkrowkqFI8MBSsTtZi5cbsf
                    l7v+/3l7OGJEM1uzAAABAQDy4Vh//8mbW9uUXJDbC/Rjf6EKXDXQfk7yDFFe/YfE3cQur8
                    MaTZGH4zdYxk/vkjvUFt2sP6KPjoyuCHj47rBWbFY2F8dY+VheWONLB3B2MEGhXqNi+9uM
                    VTjKYsa8cC81XIIi/cSrRz+m/xN2lVA6k2saDE86J0dkBDHPvNLPJD14jcgrBy8nVOSIfy
                    xGm5N86+c9FasqklZ6VPDSeOMthedUMmzF0VKF7zT7Cf3wVatzlEq/r9p0nOMA1vqRiZIu
                    7z644RdwLc+hzm2JMHSbNcaKiHzAbNrgUYaIDOvX2puuBjsXwsqyHteT8R1Bg2iCkwyMmS
                    LTY/Xz4IHn7b8rAAABAQDZ1lIao2u6u8V0iz2Fl36woFfkIUBriIGuU90cpUOVKe9EA2nK
                    L0eNjijUMuOvEo4WUegINRYfabCOMXgYLlvp8sotWKO8TjX9r7xfTDgEz7K4jkCBooizSQ
                    6Yyw3sPfstGj207uEU8VhpK5wcv639NnL23U5+fhoZsbY2mWTf6kOaKBqymidMrtreBbso
                    gA9Y8A5tTymODOJCnCOC4CTjKfG12GdeX7ML79KEfSITGwOitqCBhEtFVNTkLw3vcmiFef
                    LHLVEbcK40oVXPicsgE4D3dA5QEmgJtDUYOGQDEdRYVmtLJglmWN15WLGmtTNKl7yhcvAo
                    aEXqIBgtDU3tAAAAHWp1c3Rpbi5uZ3V5ZW5AbWluZXJhbHRyZWUuY29tAQIDBAU=
                    -----END OPENSSH PRIVATE KEY-----
        HOST: "10.1.0.59"
        USER: "jnguyen@eng-jump.mineraltree.com"
        PORT: "8081"
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        npm test
      env:
        CI: true
