name: Semantic Release

on: push

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Semantic Release
            uses: cycjimmy/semantic-release-action@v2
            with:
              dry_run: true
              extra_plugins: |
                  @semantic-release/changelog
                  @semantic-release/git
            env:
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
